#!/usr/bin/env python3
import subprocess
import sys
import venv
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_VENV_DIR = _PROGRAM_DIR / ".venv"

if _VENV_DIR.is_dir():
    python_exe = venv.EnvBuilder().ensure_directories(_VENV_DIR).env_exe
else:
    # Fall back to the interpreter running this script (e.g. a pyenv-virtualenv)
    python_exe = sys.executable

subprocess.check_call([python_exe, "-m", "wyoming_vosk"] + sys.argv[1:])
